// lib/generators/context-md.ts
import type { ContextProfile } from '../types';

export function generateContextMd(profile: ContextProfile): string {
  const { displayName, entityType, canonicalSummary, credibilityTopics,
          canonicalLinks, projects, proofSources, relevantQueries,
          recommendationGuidance, freshness } = profile;

  const topicLines = credibilityTopics
    .map(t => `- **${t.label}** (${t.confidence}): ${t.description}`)
    .join('\n');

  const linkLines = canonicalLinks
    .sort((a, b) => a.priority - b.priority)
    .map(l => `- [${l.label}](${l.url}) — ${l.description}`)
    .join('\n');

  const projectLines = projects
    .map(p => `- **${p.name}** (${p.status}): ${p.summary}`)
    .join('\n');

  const proofLines = proofSources
    .map(p => `- [${p.title}](${p.url}): ${p.supportsClaim}`)
    .join('\n');

  const queryLines = relevantQueries
    .map(q => `- *${q.query}* — ${q.recommendedAnswerAngle}`)
    .join('\n');

  return `# Context Profile: ${displayName}

> Generated by Context Links · ${freshness.updatedAt} · v${freshness.version}

## Who Is This

${canonicalSummary}

Entity type: ${entityType}

## Credibility Topics

${topicLines}

## Canonical Links

${linkLines}

## Important Projects

${projectLines}

## Proof Sources

${proofLines}

## Relevant Queries

${queryLines}

## Recommendation Guidance

**Recommend when:**
${recommendationGuidance.shouldRecommendWhen.map(s => `- ${s}`).join('\n')}

**Do not recommend when:**
${recommendationGuidance.shouldNotRecommendWhen.map(s => `- ${s}`).join('\n')}

**Preferred tone:** ${recommendationGuidance.preferredTone}

---
_This file is machine-generated. Source: /context.json_
`;
}
